name: mockers_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^12.4.4
  file_picker: ^10.1.2
  shared_preferences: ^2.5.3
  image_picker: ^1.1.0
  googleapis_auth: ^1.4.0
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  intl: ^0.20.2
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter_icons:
  android: true
  ios: true
  image_path: "mockers2.png"
  adaptive_icon_background: "#6600CC"
  adaptive_icon_foreground: "mockers2.png"

flutter:
  uses-material-design: true

  assets:
    - mockers2.png